## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [126]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from collections import Counter
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [127]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [128]:
X0, y0 = X[y == 0], y[y == 0]  
X1, y1 = X[y == 1], y[y == 1] 

In [129]:
X0_tr, X0_te, y0_tr, y0_te = train_test_split(
    X0, y0, test_size=10, random_state=42
)
X1_tr, X1_te, y1_tr, y1_te = train_test_split(
    X1, y1, test_size=10, random_state=42
)

In [130]:
X_train = np.vstack([X0_tr, X1_tr])
y_train = np.concatenate([y0_tr, y1_tr])
X_test  = np.vstack([X0_te,  X1_te])
y_test  = np.concatenate([y0_te,  y1_te])

In [131]:
X_train, y_train = shuffle(X_train, y_train, random_state=42)
X_test,  y_test  = shuffle(X_test,  y_test,  random_state=42)

In [132]:
print("y_test 分布：", Counter(y_test))

y_test 分布： Counter({0.0: 10, 1.0: 10})


In [133]:
np.set_printoptions(threshold=np.inf, linewidth=np.inf)
print("X_test.shape:", X_test.shape)
print("y_test.shape:", y_test.shape)
print("=== X_test ===\n", X_test)
print("=== y_test ===\n", y_test)
print("-" * 50)

X_test.shape: (20, 5)
y_test.shape: (20,)
=== X_test ===
 [[725 726 727 728 729]
 [135 136 137 138 139]
 [ 60  61  62  63  64]
 [740 741 742 743 744]
 [700 701 702 703 704]
 [345 346 347 348 349]
 [ 80  81  82  83  84]
 [475 476 477 478 479]
 [195 196 197 198 199]
 [185 186 187 188 189]
 [130 131 132 133 134]
 [905 906 907 908 909]
 [910 911 912 913 914]
 [ 30  31  32  33  34]
 [670 671 672 673 674]
 [ 75  76  77  78  79]
 [455 456 457 458 459]
 [ 95  96  97  98  99]
 [ 20  21  22  23  24]
 [705 706 707 708 709]]
=== y_test ===
 [0. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0.]
--------------------------------------------------
